export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const OBTENER_TRANSACIONES = 'OBTENER_TRANSACIONES';
export const AGREGAR_TRANSACION = 'AGREGAR_TRANSACION';
export const ACTUALIZAR_BALANCE = 'ACTUALIZAR_BALANCE';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';

